//Log Audit
export const LOG_AUDIT_QUERY_LOGS_COUNT_BEGIN = 'LOG_AUDIT_QUERY_LOGS_COUNT_BEGIN';
export const LOG_AUDIT_QUERY_LOGS_COUNT_SUC = 'LOG_AUDIT_QUERY_LOGS_COUNT_SUC';
export const LOG_AUDIT_QUERY_LOGS_BEGIN = 'LOG_AUDIT_QUERY_LOGS_BEGIN';
export const LOG_AUDIT_QUERY_LOGS_SUC = 'LOG_AUDIT_QUERY_LOGS_SUC';
