/**
 * Created by 周翔 on 2017/4/17.
 */
export const GROUP_QUERY_GROUPS_BEGIN = 'GROUP_QUERY_GROUPS_BEGIN'
export const GROUP_QUERY_GROUPS_SUC = 'GROUP_QUERY_GROUPS_SUC'
export const GROUP_ADD_BEGIN = 'GROUP_ADD_BEGIN'
export const GROUP_ADD_SUC = 'GROUP_ADD_SUC'
export const GROUP_UPDATE_BEGIN = 'GROUP_UPDATE_BEGIN'
export const GROUP_UPDATE_SUC = 'GROUP_UPDATE_SUC'
export const GROUP_DELETE_BEGIN = 'GROUP_DELETE_BEGIN'
export const GROUP_DELETE_SUC = 'GROUP_DELETE_SUC'
export const GROUPS_QUERY_COUNT_BEGIN = 'GROUPS_QUERY_COUNT_BEGIN'
export const GROUPS_QUERY_COUNT_SUC = 'GROUPS_QUERY_COUNT_SUC'
