//Global
export const GLOBAL_LOADING = 'GLOBAL_LOADING';
export const GLOBAL_LOGIN_DIALOG_OPEN = 'GLOBAL_LOGIN_DIALOG_OPEN';
export const GLOBAL_LOGIN_DIALOG_DISMISS = 'GLOBAL_LOGIN_DIALOG_DISMISS';
export const GLOBAL_ADD_ROUTES = 'GLOBAL_ADD_ROUTES';

//sidebar
export const SIDEBAR_MENU_OPEN = 'SIDEBAR_MENU_OPEN';
export const SIDEBAR_MENU_CLOSE = 'SIDEBAR_MENU_CLOSE';
export const SIDEBAR_MENU_TOGGLE = 'SIDEBAR_MENU_TOGGLE';

//login module
export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUC = 'LOGIN_SUC';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CHECK_BEGIN = 'LOGIN_CHECK_BEGIN';
export const LOGIN_CHECK_SUC = 'LOGIN_CHECK_SUC';
export const LOGIN_CHECK_FAIL = 'LOGIN_CHECK_FAIL';
export const LOGOUT_BEGIN = 'LOGOUT_BEGIN';
export const LOGOUT_SUC = 'LOGOUT_SUC';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

//app module
export const APP_QUERY_MENU_BEGIN = 'APP_QUERY_MENU_BEGIN';
export const APP_QUERY_MENU_SUC = 'APP_QUERY_MENU_SUC';
export const APP_QUERY_MENU_FAIL = 'APP_QUERY_MENU_FAIL';
export const APP_USER_CHANGE_PWD_SUC = 'APP_USER_CHANGE_PWD_SUC';
