//rule
export const BPMN_RULE_QUERY_BEGIN = 'BPMN_RULE_QUERY_BEGIN';
export const BPMN_RULE_QUERY_SUC = 'BPMN_RULE_QUERY_SUC';
export const BPMN_RULE_QUERY_COUNT_BEGIN = 'BPMN_RULE_QUERY_COUNT_BEGIN';
export const BPMN_RULE_QUERY_COUNT_SUC = 'BPMN_RULE_QUERYCOUNT_SUC';
export const BPMN_RULE_DEL_BEGIN = 'BPMN_RULE_DEL_BEGIN';
export const BPMN_RULE_DEL_SUC = 'BPMN_RULE_DEL_SUC';

//instance
export const BPMN_PROCESS_INSTANCE_QUERY_COMMENTS_BEGIN = 'BPMN_PROCESS_INSTANCE_QUERY_COMMENTS_BEGIN';
export const BPMN_PROCESS_INSTANCE_QUERY_COMMENTS_SUC = 'BPMN_PROCESS_INSTANCE_QUERY_COMMENTS_SUC';
export const BPMN_PROCESS_INSTANCE_QUERY_COUNT_BEGIN = 'BPMN_PROCESS_INSTANCE_QUERY_COUNT_BEGIN';
export const BPMN_PROCESS_INSTANCE_QUERY_COUNT_SUC = 'BPMN_PROCESS_INSTANCE_QUERY_COUNT_SUC';
export const BPMN_PROCESS_INSTANCE_QUERY_BEGIN = 'BPMN_PROCESS_INSTANCE_QUERY_BEGIN';
export const BPMN_PROCESS_INSTANCE_QUERY_SUC = 'BPMN_PROCESS_INSTANCE_QUERY_SUC';


//task
export const BPMN_TASK_QUERY_MY_TASKS_COUNT_BEGIN = 'BPMN_TASK_QUERY_MY_TASKS_COUNT_BEGIN';
export const BPMN_TASK_QUERY_MY_TASKS_COUNT_SUC = 'BPMN_TASK_QUERY_MY_TASKS_COUNT_SUC';
export const BPMN_TASK_QUERY_MY_TASKS_BEGIN = 'BPMN_TASK_QUERY_MY_TASKS_BEGIN';
export const BPMN_TASK_QUERY_MY_TASKS_SUC = 'BPMN_TASK_QUERY_MY_TASKS_SUC';
export const BPMN_TASK_QUERY_TRANS_BEGIN = 'BPMN_TASK_QUERY_TRANS_BEGIN';
export const BPMN_TASK_QUERY_TRANS_SUC = 'BPMN_TASK_QUERY_TRANS_SUC';
export const BPMN_TASK_TRANSFER_USER_BEGIN = 'BPMN_TASK_TRANSFER_USER_BEGIN';
export const BPMN_TASK_TRANSFER_USER_SUC = 'BPMN_TASK_TRANSFER_USER_SUC';

// his

// apply
export const BPMN_WF_APPLY_QUERY_COUNT_BEGIN = 'BPMN_WF_APPLY_QUERY_COUNT_BEGIN';
export const BPMN_WF_APPLY_QUERY_COUNT_SUC = 'BPMN_WF_APPLY_QUERY_COUNT_SUC';
export const BPMN_WF_APPLY_QUERY_BEGIN = 'BPMN_WF_APPLY_QUERY_BEGIN';
export const BPMN_WF_APPLY_QUERY_SUC = 'BPMN_WF_APPLY_QUERY_SUC';
//
// leave bpmn
export const BPMN_LEAVE_APPLY_BEGIN = 'BPMN_LEAVE_APPLY_BEGIN';
export const BPMN_LEAVE_APPLY_SUC = 'BPMN_LEAVE_APPLY_SUC';
export const BPMN_LEAVE_UPDATE_BEGIN = 'BPMN_LEAVE_UPDATE_BEGIN';
export const BPMN_LEAVE_UPDATE_SUC = 'BPMN_LEAVE_UPDATE_SUC';
export const BPMN_LEAVE_QUERY_BEGIN = 'BPMN_LEAVE_QUERY_BEGIN';
export const BPMN_LEAVE_QUERY_SUC = 'BPMN_LEAVE_QUERY_SUC';
export const BPMN_LEAVE_OUTGOING_BEGIN = 'BPMN_LEAVE_OUTGOING_BEGIN';
export const BPMN_LEAVE_OUTGOING_SUC = 'BPMN_LEAVE_OUTGOING_SUC';
