
/**
 * Created by 周翔 on 2017/4/11.
 */

export const BULLETIN_QUERY_BULLETINS_BEGIN = 'BULLETIN_QUERY_BULLETINS_BEGIN'
export const BULLETIN_QUERY_BULLETINS_SUC = 'BULLETIN_QUERY_BULLETINS_SUC'
export const BULLETIN_ADD_BEGIN = 'BULLETIN_ADD_BEGIN'
export const BULLETIN_ADD_SUC = 'BULLETIN_ADD_SUC'
export const BULLETIN_UPDATE_BEGIN = 'BULLETIN_UPDATE_BEGIN'
export const BULLETIN_UPDATE_SUC = 'BULLETIN_UPDATE_SUC'
export const BULLETIN_DELETE_BEGIN = 'BULLETIN_DELETE_BEGIN'
export const BULLETIN_DELETE_SUC = 'BULLETIN_DELETE_SUC'
export const GROUP_QUERY_GROUPS_BEGIN = 'GROUP_QUERY_GROUPS_BEGIN'
export const GROUP_QUERY_GROUPS_SUC = 'GROUP_QUERY_GROUPS_SUC'
export const BULLETINS_QUERY_COUNT_BEGIN = 'BULLETINS_QUERY_COUNT_BEGIN'
export const BULLETINS_QUERY_COUNT_SUC = 'BULLETINS_QUERY_COUNT_SUC'
export const BULLETIN_REVIEW_BEGIN = 'BULLETIN_REVIEW_BEGIN'
export const BULLETIN_REVIEW_SUC = 'BULLETIN_REVIEW_SUC'

