// APP module for mobile
export const APP_QUERY_APPS_BEGIN = 'APP_QUERY_APPS_BEGIN';
export const APP_QUERY_APPS_SUC = 'APP_QUERY_APPS_SUC';
export const APP_ADD_BEGIN = 'APP_ADD_BEGIN';
export const APP_ADD_SUC = 'APP_ADD_SUC';
export const APP_UPDATE_BEGIN = 'APP_UPDATE_BEGIN';
export const APP_UPDATE_SUC = 'APP_UPDATE_SUC';
export const APP_DELETE_BEGIN = 'APP_DELETE_BEGIN';
export const APP_DELETE_SUC = 'APP_DELTE_SUC';
export const APP_UPDATE_LIST = 'APP_UPDATE_LIST';
