/**
 * Created by shi.pengyan on 2017-01-12.
 */
//file upload
export const SYS_FILE_UPLOAD_QUERY_TOKEN = 'SYS_FILE_UPLOAD_QUERY_TOKEN';
export const SYS_FILE_UPLOAD_SAVE_FILE_BEGIN = 'SYS_FILE_UPLOAD_SAVE_FILE_BEGIN';
export const SYS_FILE_UPLOAD_SAVE_FILE_SUC = 'SYS_FILE_UPLOAD_SAVE_FILE_SUC';
export const SYS_FILE_UPLOAD_UPDATE_SUC = 'SYS_FILE_UPLOAD_UPDATE_SUC';
export const SYS_FILE_UPLOAD_DELETE_SUC = 'SYS_FILE_UPLOAD_DELETE_SUC';

export const SYS_FILE_UPLOAD_QUERY_FILES_BEGIN = 'SYS_FILE_UPLOAD_QUERY_FILES_BEGIN';
export const SYS_FILE_UPLOAD_QUERY_FILES_SUC = 'SYS_FILE_UPLOAD_QUERY_FILES_SUC';
export const SYS_FILE_UPLOAD_QUERY_FILES_COUNT_BEGIN = 'SYS_FILE_UPLOAD_QUERY_FILES_COUNT_BEGIN';
export const SYS_FILE_UPLOAD_QUERY_FILES_COUNT_SUC = 'SYS_FILE_UPLOAD_QUERY_FILES_COUNT_SUC';

// bucket
export const SYS_FILE_BUCKET_ADD_SUC = 'SYS_FILE_BUCKET_ADD_SUC';
export const SYS_FILE_BUCKET_UPDATE_SUC = 'SYS_FILE_BUCKET_UPDATE_SUC';
export const SYS_FILE_BUCKET_DEL_SUC = 'SYS_FILE_BUCKET_DEL_SUC';
export const SYS_FILE_BUCKET_QUERY_LIST_BEGIN = 'SYS_FILE_BUCKET_QUERY_BEGIN';
export const SYS_FILE_BUCKET_QUERY_LIST_SUC = 'SYS_FILE_BUCKET_QUERY_LIST_SUC';
