/**
 * Created by 周翔 on 2017/3/30.
 */

export const BANNER_QUERY_BANNERS_BEGIN = 'BANNER_QUERY_BANNERS_BEGIN'
export const BANNER_QUERY_BANNERS_SUC = 'BANNER_QUERY_BANNERS_SUC'
export const BANNER_ADD_BEGIN = 'BANNER_ADD_BEGIN'
export const BANNER_ADD_SUC = 'BANNER_ADD_SUC'
export const BANNER_UPDATE_BEGIN = 'BANNER_UPDATE_BEGIN'
export const BANNER_UPDATE_SUC = 'BANNER_UPDATE_SUC'
export const BANNER_DELETE_BEGIN = 'BANNER_DELETE_BEGIN'
export const BANNER_DELETE_SUC = 'BANNER_DELETE_SUC'
export const BANNER_ONLINE_BEGIN = 'BANNER_ONLINE_BEGIN'
export const BANNER_ONLINE_SUC = 'BANNER_ONLINE_SUC'
